version: 2
sources:
 - name: main_stg
   tables:
     - name: customers
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/customers/customers.parquet')"
     - name: products
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/products/products.parquet')"
     - name: stores
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/stores/stores.parquet')"