version: 2
sources:
 - name: main_stg
   tables:
     - name: customers
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/customers/customers.parquet')"
     - name: products
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/products/products.parquet')"
     - name: stores
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/stores/stores.parquet')"
     - name: suppliers
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/suppliers/suppliers.parquet')"
     - name: orders_header
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/orders_header/orders_header.parquet')"
     - name: orders_lines
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/orders_lines/orders_lines.parquet')"
     - name: sensors
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/sensors/sensors.parquet')"
     - name: exchange_rates
       meta:
        external_location: "read_parquet('../lake/bronze/parquet/exchange_rates/exchange_rates.parquet')"